Repository numble04/Back, pull requests merged in 2022-11, with the labels that each got.

#19 [BE] healthCheck Controller 생성
  src/main/java/com/numble/backend/common/presentation/HealthCheckController.java
Labels: 기능

#21 [BE] nginx 설정
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf.d/app.conf
  nginx/index.html
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
Labels: 설정

#23 [BE] CD 배포 자동화 구축
  .github/workflows/backend-cd.yml
  appspec.yml
  deploy.sh
Labels: 설정

#25 [BE] Comment 도메인 구현
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/domain/CommentRepository.java
  src/main/java/com/numble/backend/comment/domain/mapper/CommentMapper.java
  src/main/java/com/numble/backend/comment/dto/request/CommentRequest.java
  src/main/java/com/numble/backend/comment/dto/response/CommentResponse.java
  src/main/java/com/numble/backend/comment/exception/CommentNotFoundException.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
  src/main/java/com/numble/backend/common/dto/ResponseDto.java
  src/main/java/com/numble/backend/post/domain/Post.java
Labels: 기능

#28 [BE] post 도메인 response 리팩토링
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 리팩토링

#30 [BE] @entityGraph 적용
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/PostRepository.java
  src/main/java/com/numble/backend/post/dto/response/PostResponses.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 리팩토링

#32 [BE] jwt 예외 처리 리팩토링
  src/main/java/com/numble/backend/common/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/numble/backend/common/config/jwt/handler/JwtEntryPoint.java
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
  src/main/java/com/numble/backend/common/exception/ExceptionCode.java
  src/main/java/com/numble/backend/common/exception/auth/AuthenticationException.java
  src/main/java/com/numble/backend/common/exception/auth/ExpiredJwtException.java
  src/main/java/com/numble/backend/common/exception/auth/NoAccessTokenException.java
  src/main/java/com/numble/backend/user/presentation/UserController.java
Labels: 리팩토링

#34 [BE] 에러 코드 수정
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/exception/CommentNotFoundException.java
  src/main/java/com/numble/backend/common/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/numble/backend/common/config/jwt/handler/JwtEntryPoint.java
  src/main/java/com/numble/backend/common/exception/ExceptionCode.java
  src/main/java/com/numble/backend/common/exception/InvalidFieldException.java
  src/main/java/com/numble/backend/common/exception/auth/ExceptionCode.java
  src/main/java/com/numble/backend/common/exception/auth/ExpiredJwtException.java
  src/main/java/com/numble/backend/common/exception/business/BusinessException.java
  src/main/java/com/numble/backend/common/exception/business/InvalidFieldException.java
  src/main/java/com/numble/backend/common/presentation/ControllerAdvice.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/exception/PostNotFoundException.java
  src/main/java/com/numble/backend/user/domain/User.java
  src/main/java/com/numble/backend/user/exception/EmailExistsException.java
  src/main/java/com/numble/backend/user/exception/InvalidPasswordException.java
  src/main/java/com/numble/backend/user/exception/UserNotAuthorException.java
  src/main/java/com/numble/backend/user/exception/UserNotCreatedException.java
  src/main/java/com/numble/backend/user/exception/UserNotFoundException.java
Labels: 리팩토링

#36 [BE] redis id 저장으로 변경
  src/main/java/com/numble/backend/common/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/numble/backend/common/config/security/CustomUserDetails.java
  src/main/java/com/numble/backend/common/config/security/CustomUserDetailsService.java
  src/main/java/com/numble/backend/common/exception/auth/ExpiredJwtException.java
  src/main/java/com/numble/backend/user/application/UserService.java
Labels: 버그, 리팩토링

#38 [#37] refactor: response 형식 통일
  src/main/java/com/numble/backend/user/presentation/AuthController.java
  src/main/java/com/numble/backend/user/presentation/UserController.java
Labels: 리팩토링

#40 [#39] feat: game, theme 엔티티 작성
  src/main/java/com/numble/backend/game/domain/Game.java
  src/main/java/com/numble/backend/game/domain/Theme.java
Labels: 기능

#41 [BE] comment 기능 구현
  .github/workflows/backend-cd.yml
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/domain/CommentRepository.java
  src/main/java/com/numble/backend/comment/domain/mapper/CommentMapper.java
  src/main/java/com/numble/backend/comment/dto/request/CommentRequest.java
  src/main/java/com/numble/backend/comment/dto/response/CommentResponse.java
  src/main/java/com/numble/backend/comment/dto/response/CommentsChildrenResponse.java
  src/main/java/com/numble/backend/comment/dto/response/PostOneCommentResponse.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
  src/main/java/com/numble/backend/common/config/jpa/QuerydslConfiguration.java
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/domain/PostRepository.java
  src/main/java/com/numble/backend/post/domain/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/request/PostCreateRequest.java
  src/main/java/com/numble/backend/post/dto/response/PostOneResponse.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능, 리팩토링

#45 [BE] 게시물 등록 기능에 이미지 업로드 추가
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/domain/repository/ImageRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostLikeRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/request/PostCreateRequest.java
  src/main/java/com/numble/backend/post/exception/FileCountExceedException.java
  src/main/java/com/numble/backend/post/exception/FileUploadFailedException.java
  src/main/java/com/numble/backend/post/exception/InValidFileException.java
  src/main/java/com/numble/backend/post/exception/PostNotFoundException.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능, 리팩토링

#47 [BE] 게시물 목록 조회, 상세 조회 수정
  src/main/java/com/numble/backend/common/presentation/ControllerAdvice.java
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/domain/PostType.java
  src/main/java/com/numble/backend/post/domain/mapper/PostCreateMapper.java
  src/main/java/com/numble/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/numble/backend/post/domain/repository/ImageRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/response/PostOneResponse.java
  src/main/java/com/numble/backend/post/dto/response/PostResponse.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능, 리팩토링

#51 [BE] 게시글 좋아요 기능 & 게시글 수정 기능 구현
  src/main/java/com/numble/backend/common/utils/S3Utils.java
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/domain/PostLike.java
  src/main/java/com/numble/backend/post/domain/repository/PostLikeRepository.java
  src/main/java/com/numble/backend/post/dto/request/PostCreateRequest.java
  src/main/java/com/numble/backend/post/dto/request/PostUpdateRequest.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능

#55 [BE] 게시글 검색 기능 구현
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/mapper/PostCreateMapper.java
  src/main/java/com/numble/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/numble/backend/post/domain/mapper/PostUpdateMapper.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/request/PostRequest.java
  src/main/java/com/numble/backend/post/dto/response/PostDetailResponse.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능, 리팩토링

#57 [BE] RDS 생성 및 연결
  docker-compose.yml
Labels: 설정

#59 [BE] 댓글 좋아요 엔티티 생성
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/domain/CommentLike.java
  src/main/java/com/numble/backend/comment/domain/mapper/CommentMapper.java
  src/main/java/com/numble/backend/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/numble/backend/comment/dto/response/CommentsChildrenResponse.java
  src/main/java/com/numble/backend/comment/dto/response/PostOneCommentResponse.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
Labels: 기능, 리팩토링

#62 [BE] 댓글 수정, 삭제 기능 구현
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/numble/backend/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
Labels: 기능

#63 [BE] User 도메인 요구사항 맞춰 수정 및 추가 기능 작성
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
  src/main/java/com/numble/backend/common/utils/S3Utils.java
  src/main/java/com/numble/backend/user/application/AuthService.java
  src/main/java/com/numble/backend/user/application/UserService.java
  src/main/java/com/numble/backend/user/domain/User.java
  src/main/java/com/numble/backend/user/domain/mapper/UserInfoMapper.java
  src/main/java/com/numble/backend/user/dto/request/UserUpdateRequest.java
  src/main/java/com/numble/backend/user/dto/response/UserInfoResponse.java
  src/main/java/com/numble/backend/user/presentation/AuthController.java
  src/main/java/com/numble/backend/user/presentation/UserController.java
Labels: 기능, 리팩토링

#66 [BE] 댓글 좋아요 기능 구현
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/CommentLikeRepository.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
Labels: 기능

#74 [BE] user 회원 가입 시 region 입력 추가
  src/main/java/com/numble/backend/user/dto/request/UserCreateRequest.java
  src/main/java/com/numble/backend/user/dto/response/UserResponse.java
Labels: 기능

#75 [BE] cafe entity에 시, 구, 동 column 추가
  src/main/java/com/numble/backend/cafe/domain/Cafe.java
Labels: 기능

#77 [BE] Meeting 관련 엔티티 정의
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/MeetingLike.java
  src/main/java/com/numble/backend/meeting/domain/MeetingUser.java
Labels: 기능

#79 [BE] 모임 등록 기능 구현
  src/main/java/com/numble/backend/cafe/domain/CafeRepository.java
  src/main/java/com/numble/backend/cafe/exception/CafeNotFoundException.java
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/MeetingUser.java
  src/main/java/com/numble/backend/meeting/domain/mapper/MeetingCreateMapper.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepository.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingUserRepository.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#81 [BE] 자기 게시글 조회 기능 구현
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepository.java
  src/main/java/com/numble/backend/post/dto/response/MyPostResponse.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능

#83 [BE] 모임 조회 기능 구현
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepository.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryCustom.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingResponse.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#85 [BE] 모임 상세 조회 기능 구현
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryCustom.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingUserRepository.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingDetailResponse.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingUserResponse.java
  src/main/java/com/numble/backend/meeting/exception/MeetingNotFoundException.java
  src/main/java/com/numble/backend/meeting/exception/MeetingUserNotFoundException.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
  src/main/resources/application.yml
Labels: 기능

#89 [BE] 오타 수정
  src/main/java/com/numble/backend/comment/domain/CommentRepository.java
  src/main/java/com/numble/backend/comment/presentation/CommentController.java
Labels: 리팩토링

#90 [BE] 카페 id도 검색 반환에 포함
  src/main/java/com/numble/backend/cafe/dto/response/CafeResponse.java
Labels: 리팩토링

#93 [BE] 모임 참가, 참가 승인 및 거부 기능 구현
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/MeetingUser.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingUserRepository.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingDetailResponse.java
  src/main/java/com/numble/backend/meeting/exception/DuplicateMeetingUserException.java
  src/main/java/com/numble/backend/meeting/exception/MeetingFullException.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
  src/main/resources/application.yml
Labels: 버그, 기능

#95 [BE] 모임 나가기, 강퇴, 모임 수정, 모임 삭제 기능 구현
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/MeetingUser.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingUserRepository.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingUpdateRequest.java
  src/main/java/com/numble/backend/meeting/exception/MeetingLeaderException.java
  src/main/java/com/numble/backend/meeting/exception/MeetingUserNotApprovedException.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#102 [BE] 모임 수정, 모임 삭제, 모임 좋아요 기능 구현
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingLikeRepository.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingUpdateRequest.java
  src/main/java/com/numble/backend/meeting/exception/MeetingUpdateException.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#106 [BE] 이미지 리사이징 기능 구현
  build.gradle
  src/main/java/com/numble/backend/common/exception/business/FileUploadFailedException.java
  src/main/java/com/numble/backend/common/exception/business/InValidFileException.java
  src/main/java/com/numble/backend/common/utils/S3Utils.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingUpdateRequest.java
  src/main/resources/application.yml
Labels: 버그, 기능, 리팩토링

#108 [BE] User 도메인에 자기소개 추가
  src/main/java/com/numble/backend/user/domain/User.java
  src/main/java/com/numble/backend/user/dto/request/UserUpdateRequest.java
  src/main/java/com/numble/backend/user/dto/response/UserInfoResponse.java
Labels: 리팩토링

#110 [BE] redis 토큰 cache 추가
  src/main/java/com/numble/backend/common/config/security/CustomUserDetails.java
  src/main/java/com/numble/backend/common/config/security/CustomUserDetailsService.java
Labels: 기능

#112 게임 조회에 Local Cache 적용
  build.gradle
  src/main/java/com/numble/backend/common/config/cache/CacheConfig.java
  src/main/java/com/numble/backend/common/config/cache/CacheType.java
  src/main/java/com/numble/backend/common/config/redis/CacheConfig.java
  src/main/java/com/numble/backend/common/config/security/SecurityConfig.java
  src/main/java/com/numble/backend/game/presentation/GameController.java
Labels: 설정, 기능

#115 [BE] dto 동사 이름 앞에 오는 것 전부 변경
  src/main/java/com/numble/backend/game/application/GameReviewService.java
  src/main/java/com/numble/backend/game/application/GameService.java
  src/main/java/com/numble/backend/game/domain/GameReview.java
  src/main/java/com/numble/backend/game/domain/mapper/GameDetailMapper.java
  src/main/java/com/numble/backend/game/domain/mapper/GameReviewCreateMapper.java
  src/main/java/com/numble/backend/game/domain/mapper/GetDetailGameResponseMapper.java
  src/main/java/com/numble/backend/game/domain/mapper/PostGameReviewRequestMapper.java
  src/main/java/com/numble/backend/game/domain/repository/GameRepository.java
  src/main/java/com/numble/backend/game/domain/repository/GameRepositoryCustom.java
  src/main/java/com/numble/backend/game/domain/repository/GameRepositoryImpl.java
  src/main/java/com/numble/backend/game/domain/repository/GameReviewRepositoryCustom.java
  src/main/java/com/numble/backend/game/domain/repository/GameReviewRepositoryImpl.java
  src/main/java/com/numble/backend/game/dto/request/GameReviewCreateRequest.java
  src/main/java/com/numble/backend/game/dto/request/GameReviewUpdateRequest.java
  src/main/java/com/numble/backend/game/dto/response/GameDetailResponse.java
  src/main/java/com/numble/backend/game/dto/response/GameResponse.java
  src/main/java/com/numble/backend/game/dto/response/ReviewResponse.java
  src/main/java/com/numble/backend/game/presentation/GameController.java
Labels: 리팩토링

#117 [BE] 모임 조회 기능 수정
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
Labels: 기능

#119 [BE] 자신의 모임 조회 기능 구현
  docker-compose.yml
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryCustom.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/dto/response/MyMeetingResponse.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#120 [BE] Game, GameDetail dto 변경
  src/main/java/com/numble/backend/game/domain/repository/GameRepositoryImpl.java
  src/main/java/com/numble/backend/game/dto/response/GameDetailResponse.java
  src/main/java/com/numble/backend/game/dto/response/GameResponse.java
Labels: 리팩토링

#122 [BE] 좋아요 누른 게시글 조회 기능 구현
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Post.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/response/MyPostResponse.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
  src/main/resources/application.yml
Labels: 버그, 기능, 리팩토링

#124 [BE] 좋아요 누른 모임 조회
  docker-compose.yml
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryCustom.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#126 [BE] post 관련 쿼리 최적화
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/Image.java
  src/main/java/com/numble/backend/post/domain/PostLike.java
  src/main/java/com/numble/backend/post/domain/mapper/PostCreateMapper.java
  src/main/java/com/numble/backend/post/domain/repository/ImageRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostLikeRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepository.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/dto/request/PostCreateRequest.java
  src/main/java/com/numble/backend/post/dto/request/PostUpdateRequest.java
  src/main/java/com/numble/backend/post/dto/response/MyPostResponse.java
  src/main/java/com/numble/backend/post/dto/response/PostDetailResponse.java
  src/main/java/com/numble/backend/post/dto/response/PostResponse.java
  src/main/java/com/numble/backend/post/exception/PostNotFoundException.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 리팩토링

#128 [BE] comment 관련 코드 정리
  src/main/java/com/numble/backend/comment/application/CommentService.java
  src/main/java/com/numble/backend/comment/domain/Comment.java
  src/main/java/com/numble/backend/comment/domain/CommentLike.java
  src/main/java/com/numble/backend/comment/domain/CommentRepository.java
  src/main/java/com/numble/backend/comment/domain/mapper/CommentMapper.java
  src/main/java/com/numble/backend/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/numble/backend/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/numble/backend/comment/dto/response/CommentResponse.java
  src/main/java/com/numble/backend/comment/dto/response/CommentsChildrenResponse.java
  src/main/java/com/numble/backend/comment/dto/response/PostOneCommentResponse.java
Labels: 리팩토링

#130 [BE] Meeting 관련 코드 정리
  src/main/java/com/numble/backend/common/config/security/CustomUserDetails.java
  src/main/java/com/numble/backend/meeting/application/MeetingService.java
  src/main/java/com/numble/backend/meeting/domain/Meeting.java
  src/main/java/com/numble/backend/meeting/domain/MeetingUser.java
  src/main/java/com/numble/backend/meeting/domain/mapper/MeetingCreateMapper.java
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/com/numble/backend/meeting/dto/request/MeetingUpdateRequest.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingDetailResponse.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingResponse.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingUserResponse.java
  src/main/java/com/numble/backend/meeting/dto/response/MyMeetingResponse.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 리팩토링

#137 [BE] jwt secret 설정 변경
  src/main/resources/application.yml
Labels: 설정

#135 [BE] 같은 game에 대한 리뷰를 한 user가 여러 개 작성하는 문제 해결
  src/main/java/com/numble/backend/game/application/GameReviewService.java
  src/main/java/com/numble/backend/game/domain/repository/GameRepository.java
  src/main/java/com/numble/backend/game/domain/repository/GameReviewRepository.java
  src/main/java/com/numble/backend/game/exception/GameReviewExistException.java
Labels: 버그

#140 [BE] CORS 에러 method 설정
  src/main/java/com/numble/backend/common/config/WebConfig.java
Labels: 버그

#142 [BE] 게시물 검색 기능 수정
  src/main/java/com/numble/backend/post/application/PostService.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryCustom.java
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
  src/main/java/com/numble/backend/post/presentation/PostController.java
Labels: 기능

#144 [BE] 자기 댓글 조회 시 생성 시간 및 수정 시간 추가
  src/main/java/com/numble/backend/comment/dto/response/CommentResponse.java
Labels: 기능

#146 [BE] 도커 컴포즈에 환경변수 추가
  docker-compose.yml
Labels: 설정

#148 [BE] 모임 조회시 동적쿼리 버그 수정
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
Labels: 버그

#154 [BE] 모임 상세 조회시 카페 주소 추가
  src/main/java/com/numble/backend/meeting/dto/response/MeetingDetailResponse.java
Labels: 기능

#156 [BE] 모임 생성시 id 반환하도록 수정
  src/main/java/com/numble/backend/meeting/dto/response/MeetingCreateResponse.java
  src/main/java/com/numble/backend/meeting/presentation/MeetingController.java
Labels: 기능

#158 [BE] 모임 상세 조회에 자신의 승인 여부 추가
  src/main/java/com/numble/backend/meeting/domain/repository/MeetingRepositoryImpl.java
  src/main/java/com/numble/backend/meeting/dto/response/MeetingDetailResponse.java
Labels: 기능

#160 [#159] image 삭제 시 ""로 저장되는 버그 수정
  src/main/java/com/numble/backend/user/domain/User.java
Labels: 버그

#162 [BE] 게시글 조회시 좋아요 버그 수정
  src/main/java/com/numble/backend/post/domain/repository/PostRepositoryImpl.java
Labels: 버그
